### PR TITLE
Arctic Horizon 2 style next-episode window

### PR DESCRIPTION
**Pull request by OneAngryMan**
Hi,
I'm not sure you're even taking pull requests, but I figured I might as well give this a shot. I've been using AH2 and Fen for a while now, and one of the few things that was bothering me, was the lack of a next-episode window in the same style as my skin. Both Seren and Umbrella already have this, Fen doesn't. I'm hoping that's only because it's not a priority for you and not that you just don't want Fen to get bloated up with stuff like this. Either way, this is what it looks like: 
Screenshot (490)
I had to add a couple lines to your code, to allow for a window-style setting, I'll quickly list the changed stuff below. The ah2 style xml file also works with autoscrape, but the respective setting is still missing (just realized that while testing), I can add that if necessary, but I personally don't use the feature and figured I should better check out if you even deem this Fen-worthy before devoting more time to it.

Edit: Window-style setting should now work with autoscrape as well, I've updated the changes below.

Changed files:
```
###### strings.po ######
msgctxt "#40010"
msgid "Next Episode Window Style"
msgstr ""

msgctxt "#40011"
msgid "Classic"
msgstr ""

msgctxt "#40012"
msgid "Arctic Horizon 2"
msgstr ""

###### settings.xml ######
<setting id="autoscrape_next_episode" type="boolean" label="33086" help="">
	<level>0</level>
	<default>false</default>
	<dependencies>
		<dependency type="visible">
			<condition operator="is" setting="auto_play_episode">false</condition>
		</dependency>
	</dependencies>
	<control type="toggle"/>
</setting>
<setting id="auto_nextep_window_style" type="string" label="40010" help="" parent="autoplay_next_episode">
	<level>0</level>
	<default>next_episode.xml</default>
	<constraints>
		<options>
			<option label="40011">next_episode.xml</option>
			<option label="40012">next_episode_ah2.xml</option>
		</options>
	</constraints>
	<dependencies>
		<dependency type="visible">
			<or>
				<and>
					<condition operator="is" setting="auto_play_episode">true</condition>
					<condition operator="is" setting="autoplay_next_episode">true</condition>
					<condition operator="is" setting="autoplay_alert_method">0</condition>
				</and>
				<and>
					<condition operator="is" setting="auto_play_episode">false</condition>
					<condition operator="is" setting="autoscrape_next_episode">true</condition>
				</and>
			</or>
		</dependency>
	</dependencies>
	<control type="spinner" format="string"/>
</setting>

###### settings.py ######
def auto_nextep_settings():
	...
	window_style = str(get_setting('auto_nextep_window_style', '0'))
	default_action = default_action_dict[int(get_setting('autoplay_default_action', '1'))] if alert_method == 0 else 'cancel'
	return {'scraper_time': scraper_time, 'window_percentage': window_percentage, 'alert_method': alert_method, 'window_style': window_style, 'default_action': default_action}

###### player.py ######
	def info_next_ep(self):
		...
			window_style = nextep_settings['window_style']
			self.start_prep = nextep_settings['scraper_time'] + window_time
			self.nextep_settings = {'use_window': use_window, 'window_time': window_time, 'default_action': default_action, 'play_type': play_type, 'window_style': window_style}
		except: pass

###### sources.py ######
	def autoscrape_nextep_handler(self):
		default_action = 'cancel'
		if self.player.isPlayingVideo():
			window_style = self.nextep_settings['window_style']
			action = self._make_nextep_dialog(play_type=self.play_type, focus_button=12, window_style=window_style)
			...

	def autoplay_nextep_handler(self):
		...
			window_style = self.nextep_settings['window_style']
			action = None if use_window else 'close'
			while self.player.isPlayingVideo():
				try:
					if round(total_time - self.player.getTime()) <= window_time: break
					sleep(100)
				except: pass
			if use_window: action = self._make_nextep_dialog(default_action=default_action, window_style=window_style)
			...

	def _make_nextep_dialog(self, default_action='cancel', play_type='autoplay_nextep', focus_button=10, window_style='next_episode.xml'):
		try: action = open_window(('windows.next_episode', 'NextEpisode'), window_style,
			meta=self.meta, default_action=default_action, play_type=play_type, focus_button=focus_button)
		...

###### next_episode.py ######
	def set_properties(self):
		...
		self.setProperty('next_ep_title', self.meta['title'])
		self.setProperty('next_ep_season', '%02d' % self.meta['season'])
		self.setProperty('next_ep_episode', '%02d' % self.meta['episode'])
		self.setProperty('next_ep_ep_name', self.meta['ep_name'])

###### next_episode.xml ######
                    <control type="textbox">
			...
                        <label>[B]$INFO[Window.Property(next_ep_title)] - $INFO[Window.Property(next_ep_season)]x$INFO[Window.Property(next_ep_episode)][/B] - $INFO[Window.Property(next_ep_ep_name)]</label>
                        <autoscroll>true</autoscroll>
                    </control>

###### next_episode_ah2.xml ######
<?xml version="1.0" encoding="UTF-8"?>
<window>
    <onload>Dialog.Close(fullscreeninfo,true)</onload>
    <onload>Dialog.Close(videoosd,true)</onload>
    <include>Animation_FadeIn</include>
    <controls>
        <control type="image">
            <height>400</height>
            <texture>special://skin/media/common/dim-top-bezier.png</texture>
        </control>
        <control type="group">
            <include>Dimension_UpNext</include>
            <control type="group">
                <width>upnext_image_w</width>
                <control type="image">
                    <texture diffuse="special://skin/media/diffuse/landscape_w284_h160.png">$INFO[Window.Property(fanart)]</texture>
                    <aspectratio scalediffuse="false">scale</aspectratio>
                </control>
                <control type="progress" id="5000">
                    <bottom>0</bottom>
                    <height>8</height>
                </control>
            </control>
            <control type="group">
                <left>upnext_image_w</left>
                <control type="label">
                    <visible>String.IsEqual(Window.Property(play_type),autoplay_nextep)</visible>
                    <left>40</left>
                    <aligny>center</aligny>
                    <height>40</height>
                    <label>$ADDON[plugin.video.fen 32811] [COLOR $INFO[Skin.String(focuscolor.name)]]$INFO[Player.TimeRemaining(m:ss)][/COLOR]</label>
                    <textcolor>panel_fg_100</textcolor>
                    <font>font_midi_bold</font>
                </control>
                <control type="label">
                    <visible>String.IsEqual(Window.Property(play_type),autoscrape_nextep)</visible>
                    <left>40</left>
                    <aligny>center</aligny>
                    <height>40</height>
                    <label>$ADDON[plugin.video.fen 33086]?</label>
                    <textcolor>panel_fg_100</textcolor>
                    <font>font_midi_bold</font>
                </control>
                <control type="group">
                    <left>44</left>
                    <top>40</top>
                    <height>40</height>
                    <control type="group">
                        <centertop>50%</centertop>
                        <height>80</height>
                        <control type="image">
                            <aspectratio align="left">keep</aspectratio>
                            <texture colordiffuse="panel_fg_90">special://skin/media/flags/quality/info.png</texture>
                            <centertop>52%</centertop>
                            <width>37</width>
                            <height>24</height>
                        </control>
                        <control type="grouplist">
                            <left>47</left>
                            <orientation>horizontal</orientation>
                            <height>80</height>
                            <itemgap>10</itemgap>
                            <include content="Info_Line_Label">
                                <param name="label" value="$INFO[Window.Property(next_ep_title)]" />
                                <param name="textcolor" value="panel_fg_90" />
                                <param name="font" value="font_mini_bold" />
                            </include>
                            <include content="Info_Line_Label">
                                <param name="label" value="$INFO[Window.Property(next_ep_season)]x$INFO[Window.Property(next_ep_episode)]" />
                                <param name="textcolor" value="panel_fg_90" />
                                <param name="font" value="font_mini_bold" />
                            </include>
                            <include content="Info_Line_Label">
                                <param name="label" value="$INFO[Window.Property(next_ep_ep_name)]" />
                                <param name="textcolor" value="panel_fg_90" />
                                <param name="font" value="font_mini_bold" />
                            </include>
                        </control>
                    </control>
                </control>
                <control type="group">
                    <height>70</height>
                    <bottom>0</bottom>
                    <control type="grouplist">
                        <visible>String.IsEqual(Window.Property(play_type),autoplay_nextep)</visible>
                        <itemgap>-60</itemgap>
                        <orientation>horizontal</orientation>
                        <height>256</height>
                        <centertop>50%</centertop>
                        <include content="Object_Info_Button">
                            <param name="id" value="10" />
                            <param name="groupid" value="5012" />
                            <param name="sliceid" value="5112" />
                            <param name="label" value="$ADDON[plugin.video.fen 32614]" />
                            <param name="icon" value="special://skin/extras/icons/eye2.png" />
                        </include>
                        <include content="Object_Info_Button">
                            <param name="id" value="11" />
                            <param name="groupid" value="5013" />
                            <param name="sliceid" value="5113" />
                            <param name="label" value="$ADDON[plugin.video.fen 32764]" />
                            <param name="icon" value="special://skin/extras/icons/play3.png" />
                        </include>
                        <include content="Object_Info_Button">
                            <param name="id" value="12" />
                            <param name="groupid" value="5014" />
                            <param name="sliceid" value="5114" />
                            <param name="label" value="$ADDON[plugin.video.fen 32840]" />
                            <param name="icon" value="special://skin/extras/icons/disabled.png" />
                        </include>
                    </control>
                    <control type="grouplist">
                        <visible>String.IsEqual(Window.Property(play_type),autoscrape_nextep)</visible>
                        <itemgap>-60</itemgap>
                        <orientation>horizontal</orientation>
                        <height>256</height>
                        <centertop>50%</centertop>
                        <include content="Object_Info_Button">
                            <param name="id" value="10" />
                            <param name="groupid" value="5012" />
                            <param name="sliceid" value="5112" />
                            <param name="label" value="$ADDON[plugin.video.fen 33090]" />
                            <param name="icon" value="special://skin/extras/icons/play3.png" />
                        </include>
                        <include content="Object_Info_Button">
                            <param name="id" value="11" />
                            <param name="groupid" value="5013" />
                            <param name="sliceid" value="5113" />
                            <param name="label" value="$ADDON[plugin.video.fen 32824]" />
                            <param name="icon" value="special://skin/extras/icons/eye2.png" />
                        </include>
                        <include content="Object_Info_Button">
                            <param name="id" value="12" />
                            <param name="groupid" value="5014" />
                            <param name="sliceid" value="5114" />
                            <param name="label" value="$ADDON[plugin.video.fen 32828]" />
                            <param name="icon" value="special://skin/extras/icons/disabled.png" />
                        </include>
                    </control>
                </control>
            </control>
        </control>
    </controls>
</window>
```

### CODE REVIEW

**Comment by Tikipeter** [comment]
>and not that you just don't want Fen to get bloated up with stuff like this

Unfortunately, this is the reason nothing has been done on this front.

But, I really appreciate the effort you have put into this, so I'm going to have a good think about it and come up with a solution so that it can be implemented. I just don't want extra, specific skin related xmls in the addons xml folder.

I've implented something so that the custom xmls can be housed in Fen's userdata folder instead, so they are accessible and will also survive a Fen update.

I'll keep you posted....

**Comment by Tikipeter** [comment]
The update will be in the testing repo if you want to try it out and make sure it works OK.

**Comment by ViewAfterReview** [comment]
> I may code an install method if there's any interest. The custom xml's could be zipped up in this folder format, then installed from the zip.

That would be great for installing on android devices!

**Comment by Tikipeter** [comment]
I've added a function to download the custom skins lol!

I'm sorry mate. You keep putting in all this effort and then I come along and do something else.

My apologies.

Next update will have a setting:

screenshot00000


Set that to "True", and all the current custom skin xmls will be downloaded (currently only yours of course).

I'm using a `custom_skins.zip` file from my repo. If anyone wants to submit some xmls for any skins, I can add them to that zip file.

I jut need to implement a way to notify Fen that there is an updated zip. Likely use a value in a text file, similar to Kodi with it's md5 value for updates check.

I can then run this check once on startup, and also when the user toggles from False to True.

**Comment by Tikipeter** [comment]
This will be ready for next update, with a service run at startup to check for an updated custom_skins zip from my github.

Much thanks to @OneAngryMan for his effort in making this possible. Whilst I had nothing against custom xmls, it was not something I was going to delve into myself unless pushed in that direction. So kudos for getting the ball rolling.

Seems like most interest will be for a custom next_episode.xml, so maybe there are more out there who want to give it a try for their skin of choice. We'll see.....

**Comment by Liquidrag** [comment]
Thank you @Tikipeter and @OneAngryMan! I look forward to the update.

**Comment by ShibajiCh** [comment]
Thank you both @OneAngryMan and @Tikipeter. Looking forward to the release of the new update soon! 🙂👍🏻

**Comment by ShibajiCh** [comment]
Hi @OneAngryMan and @Tikipeter,

The new Playing Next Dialog is looking awesome in Fen v3.0.42. Thank you both!

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
> I noticed is that there's no deletion of preexisting files in the custom_skins folder

You're right. I'll add deletion of current contents during the update for next version.

**Pull request closed without merging**
